apiVersion: v1
kind: Pod
metadata:
  name: hugo-server
  labels:
    app: blog
spec:
  containers:
    - name: hugo-server
      image: blog-hugo-backend:latest
      command: ["hugo"]
      args: ["server", "-v", "-D"]
      ports:
        - containerPort: 1313
          name: "hugo-server"
      imagePullPolicy: Never    
  restartPolicy: OnFailure
