apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: hugo-service
  namespace: hugo
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "hugo-server-port"
      port: 1313
      protocol: TCP
      targetPort: 1313
  selector:
    app: blog
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
