apiVersion: v1
kind: Pod
metadata:
  name: hugo-server
  labels:
    app: blog
spec:
  containers:
    - name: hugo-server
      image: klakegg/hugo
      command: ["sleep"]
      args: ["300"]
      # command: ["hugo"]
      # args: ["server", "-v", "--config", "/src/config.toml", "-D"]
      volumeMounts:
        - mountPath: "/src"
          name: backend-files-volume
      ports:
        - containerPort: 1313
          name: "hugo-server"    
  volumes:
    - name: backend-files-volume
      hostPath:
        path: "/run/desktop/mnt/wsl/blog-hugo-backend"
        type: Directory
  restartPolicy: OnFailure
