apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-server-deployment
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
        labels:
          app: blog
    spec:
      containers:
        - name: hugo-server
          image: blog-hugo-backend:latest
          command: ["hugo"]
          args: ["server", "-v", "-D"]
          ports:
          - containerPort: 1313
            name: "hugo-server"
          imagePullPolicy: Never