apiVersion: v1
kind: Pod
metadata:
  name: hugo-server
  labels:
    app: blog
spec:
  containers:
    - name: hugo-server
      image: klakegg/hugo
      command: ["hugo"]
      args: ["server", "-D"]
  restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-files-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
