apiVersion: v1
kind: Pod
metadata:
  name: hugo-server
  labels:
    app: blog
spec:
  containers:
    - name: hugo-server
      image: klakegg/hugo
      command: ["hugo"]
      args: ["server", "-D"]
  restartPolicy: OnFailure