apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: blog-hugo-cluster
build:
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: blog-hugo-backend
  local: {}
deploy:
  kubectl:
    manifests:
    - blog-hugo-cluster/hugo-namespace.yaml
    - blog-hugo-cluster/hugo-deployment.yaml
    - blog-hugo-cluster/hugo-service.yaml
